FROM php:8.1-apache

WORKDIR /var/www/html/

EXPOSE 80 443 9003

RUN chown -R www-data:www-data /var/www

#Pacotes
RUN apt-get update \
    && apt-get install -y libxml2-dev \
    && apt-get install -y libpng-dev

#Zip Suport
RUN apt-get install -y \
    libzip-dev \
    zip \
    && docker-php-ext-install zip

#IMAP
RUN apt-get install -y libc-client-dev libkrb5-dev \
    && rm -r /var/lib/apt/lists/* \
    && docker-php-ext-configure imap --with-kerberos --with-imap-ssl \ 
    && docker-php-ext-install imap

#Extensões PHP
RUN docker-php-ext-install mysqli pdo pdo_mysql
RUN docker-php-ext-install bcmath
RUN docker-php-ext-install soap

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

#X-Debug
RUN BEFORE_PWD=$(pwd) \
    && mkdir -p /opt/xdebug \
    && cd /opt/xdebug \
    && curl -k -L https://github.com/xdebug/xdebug/archive/3.1.4.tar.gz | tar zx \
    && cd xdebug-3.1.4 \
    && phpize \
    && ./configure --enable-xdebug \
    && make clean \
    && sed -i 's/-O2/-O0/g' Makefile \
    && make \
    # && make test \
    && make install \
    && cd "${BEFORE_PWD}" \
    && rm -r /opt/xdebug
RUN docker-php-ext-enable xdebug

#Apache
RUN a2enmod rewrite

